// <auto-generated />
using System;
using AndreAirlinesAPI2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AndreAirlinesAPI2._0.Migrations
{
    [DbContext(typeof(AndreAirlinesAPI2_0Context))]
    [Migration("20220402125429_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Airport", b =>
                {
                    b.Property<string>("Acronym")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Acronym");

                    b.HasIndex("AddressId");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Airship", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airship");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.BasePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("DestinyAcronym")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginAcronym")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("PercentPromotion")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("DestinyAcronym");

                    b.HasIndex("OriginAcronym");

                    b.ToTable("BasePrice");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirshipId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinyAcronym")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DisembarkationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginAcronym")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AirshipId");

                    b.HasIndex("DestinyAcronym");

                    b.HasIndex("OriginAcronym");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Passenger", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cpf");

                    b.HasIndex("AddressId");

                    b.ToTable("Passenger");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("PassengerCpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerCpf");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Airport", b =>
                {
                    b.HasOne("AndreAirlinesAPI2._0.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.BasePrice", b =>
                {
                    b.HasOne("AndreAirlinesAPI2._0.Model.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("AndreAirlinesAPI2._0.Model.Airport", "Destiny")
                        .WithMany()
                        .HasForeignKey("DestinyAcronym");

                    b.HasOne("AndreAirlinesAPI2._0.Model.Airport", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginAcronym");

                    b.Navigation("Class");

                    b.Navigation("Destiny");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Flight", b =>
                {
                    b.HasOne("AndreAirlinesAPI2._0.Model.Airship", "Airship")
                        .WithMany()
                        .HasForeignKey("AirshipId");

                    b.HasOne("AndreAirlinesAPI2._0.Model.Airport", "Destiny")
                        .WithMany()
                        .HasForeignKey("DestinyAcronym");

                    b.HasOne("AndreAirlinesAPI2._0.Model.Airport", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginAcronym");

                    b.Navigation("Airship");

                    b.Navigation("Destiny");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Passenger", b =>
                {
                    b.HasOne("AndreAirlinesAPI2._0.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("AndreAirlinesAPI2._0.Model.Ticket", b =>
                {
                    b.HasOne("AndreAirlinesAPI2._0.Model.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("AndreAirlinesAPI2._0.Model.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.HasOne("AndreAirlinesAPI2._0.Model.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerCpf");

                    b.Navigation("Class");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });
#pragma warning restore 612, 618
        }
    }
}
